### ISSUE TITLE
run_han.py Example - Error processing the entire json file

### ISSUE THREAD

**Issue by truas** [Hsankesara/DeepResearch#1]
**Describe the bug**
I'm trying to run the example with run_han.py, but for the entire json file, not just the first 500 entries. However, I keep receiving an error on the preprocessing step:

` if k < self.max_senten_len and tokenizer.word_index[word] < self.max_features`

**To Reproduce**
1. Alter run_han.py to run for the entire dataset not only the first 500 items
2. I removed the shuffle before the read_json to reproduce the problem

**Expected behavior**
I was hoping to use HAN for the entire dataset. The notebook example seems to work just fine.

**Screenshots**
 Keep getting this stack:
`See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
Traceback (most recent call last):
  File "C:\Users\terry\Documents\Datasets\HAN\DeepResearch-master\Hierarchical_Attention_Network\run_han.py", line 39, in <module>
    main()
  File "C:\Users\terry\Documents\Datasets\HAN\DeepResearch-master\Hierarchical_Attention_Network\run_han.py", line 24, in main
    han_network = HAN.HAN(text = df.text, labels = df.category, num_categories = 30, pretrained_embedded_vector_path = 'C:\\Users\\terry\\Documents\\Datasets\\GloVe\\glove.6B\\glove.6B.100d.txt', max_features = 200000, max_senten_len = 150, max_senten_num = 4 , embedding_size = 100, validation_split=0.2, verbose=1)
  File "C:\Users\terry\Documents\Datasets\HAN\DeepResearch-master\Hierarchical_Attention_Network\HAN.py", line 68, in __init__
    self.data, self.labels = self.preprocessing()
  File "C:\Users\terry\Documents\Datasets\HAN\DeepResearch-master\Hierarchical_Attention_Network\HAN.py", line 133, in preprocessing
    if k < self.max_senten_len and tokenizer.word_index[word] < self.max_features:
KeyError: 'gratisography'
`
If I use the shuffle function, before the reading the token displayed changes.

I was thinking this was because of the encoding, but I might be wrong.

**Desktop (please complete the following information):**
 - OS: W10.
 - Version: Python 3.6

**Comment by Hsankesara** [comment]
Hey @truas 
There was a little bug in the code. I fixed it now (check out #2). Please run it again and if you still face error please let me know.
Thank you for the issue.

**Comment by truas** [comment]
Hello @Hsankesara ,

It seems everything is running smoothly now. I just added the encoding for opening the embeddings models used (encoding='utf-8').

Thank you,
T.
